#pragma once

#include "Problem.h"
#include "Variable.h"
#include "Operation.h"
#include "Example.h"
#include "Array.h"
#include "String.h"
#include "Structure.h"
#include "Pointer.h"
#include "Dynamic.h"
#include "Class.h"
#include "ArrayClass.h"
#include "StringClass.h"
#include "VectorClass.h"
#include "VirtualFunction.h"
#include "PureVirtualFunction.h"
#include "Template.h"
#include "MiniProject.h"
#include "ScissorsRockPaper.h"
#include "Lotto.h"
#include "Baseball.h"
#include "TowerOfHanoi.h"

